In [1]:
import pandas as pd
import glob
import os

In [23]:

# Define the path pattern for CSV files
path_pattern = '/Users/andysh.to/Script/Python_Script/eis_flare_project_esa_computer/flare_dfs/filtered_flares_2*.csv'

# Get list of all matching CSV files
csv_files = glob.glob(path_pattern)

# Read and concatenate all CSV files into one dataframe
dfs = []
for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)
    
# Combine all dataframes
combined_df = pd.concat(dfs, ignore_index=True)

# Optional: Sort by date if there's a date column
# combined_df = combined_df.sort_values('date_column_name')

In [24]:
combined_df['stud_acr']

0         Flare266_Hunter01
1                  Atlas_60
2         Flare266_Hunter01
3         Flare266_Hunter01
4         Flare266_Hunter01
               ...
705     cam_ar_limb_lite_v3
706    HPW021_VEL_240x512v1
707    HPW021_VEL_240x512v1
708    HPW021_VEL_240x512v1
709    HPW021_VEL_240x512v2
Name: stud_acr, Length: 710, dtype: object

In [25]:
# Filter the dataframe to only include rows where 'stud_acr' starts with 'Altas'
filtered_df = combined_df[combined_df['stud_acr'].str.startswith('Atlas', na=False)]
filtered_df

,study ID,flare times,GOES class,hpc x,hpc y,EIS xcen,EIS ycen,EIS fovx,EIS fovy,target,stud_acr,filename,EIS xmin,EIS xmax,EIS ymin,EIS ymax
1,404,2023-02-09 12:20:50,C8.4,226.114515,592.661631,236.604996,583.794006,119.807999,160.0,Quiet Sun,Atlas_60,eis_20230209_122050.data.h5,176.700996,296.508995,503.794006,663.794006
11,404,2023-04-13 00:07:02,C4.0,40.691096,-232.021582,-14.057000,-286.865997,119.807999,160.0,Quiet Sun,Atlas_60,eis_20230413_000702.data.h5,-73.960999,45.846999,-366.865997,-206.865997
15,404,2023-05-10 14:07:44,M2.2,670.942131,263.190417,613.252991,242.753006,119.807999,160.0,Quiet Sun,Atlas_60,eis_20230510_140744.data.h5,553.348991,673.156990,162.753006,322.753006
23,404,2023-05-21 23:55:18,C8.2,-514.125840,323.252654,-561.046997,304.997009,119.807999,160.0,Quiet Sun,Atlas_60,eis_20230521_235518.data.h5,-620.950996,-501.142998,224.997009,384.997009
24,404,2023-05-23 07:01:47,C2.3,-279.806431,328.104618,-329.031006,307.315002,119.807999,160.0,Quiet Sun,Atlas_60,eis_20230523_070147.data.h5,-388.935005,-269.127007,227.315002,387.315002
27,404,2023-05-24 19:12:41,C5.1,3.320805,366.961252,-15.982300,298.131012,119.807999,160.0,Quiet Sun,Atlas_60,eis_20230524_191241.data.h5,-75.886299,43.921700,218.131012,378.131012
51,404,2022-04-21 12:50:13,C5.4,-318.983796,321.250288,-304.621002,345.454987,119.807999,160.0,Quiet Sun,Atlas_60,eis_20220421_125013.data.h5,-364.525002,-244.717003,265.454987,425.454987
54,404,2022-04-28 23:41:08,C1.2,908.003901,230.528214,868.919006,268.834015,119.807999,160.0,Quiet Sun,Atlas_60,eis_20220428_234108.data.h5,809.015007,928.823006,188.834015,348.834015
62,404,2022-05-26 12:24:42,C1.6,844.022005,203.078171,806.900024,179.438004,119.807999,160.0,Quiet Sun,Atlas_60,eis_20220526_122442.data.h5,746.996025,866.804024,99.438004,259.438004
69,404,2022-07-24 14:21:13,B4.9,784.446421,125.492067,741.793030,134.914993,119.807999,160.0,Quiet Sun,Atlas_60,eis_20220724_142113.data.h5,681.889030,801.697029,54.914993,214.914993
71,404,2022-07-29 14:01:13,B2.3,-513.531629,256.119982,-518.026978,226.729004,119.807999,160.0,Quiet Sun,Atlas_60,eis_20220729_140113.data.h5,-577.930977,-458.122978,146.729004,306.729004
80,404,2022-10-02 11:03:20,C2.4,-836.228440,335.517527,-792.304016,327.319000,119.807999,160.0,Quiet Sun,Atlas_60,eis_20221002_110320.data.h5,-852.208015,-732.400017,247.319000,407.319000
81,404,2022-10-02 11:03:20,C3.0,-836.834387,333.118342,-792.304016,327.319000,119.807999,160.0,Quiet Sun,Atlas_60,eis_20221002_110320.data.h5,-852.208015,-732.400017,247.319000,407.319000
98,404,2020-04-09 08:38:43,B1.6,717.100898,514.454679,675.604004,499.929993,119.807999,160.0,Quiet Sun,Atlas_60,eis_20200409_083843.data.h5,615.700005,735.508003,419.929993,579.929993
101,404,2020-10-27 15:50:40,B7.9,367.229246,-429.764362,331.200989,-444.820007,119.807999,160.0,Quiet Sun,Atlas_60,eis_20201027_155040.data.h5,271.296989,391.104988,-524.820007,-364.820007
102,404,2020-10-28 01:05:13,C1.1,461.896696,-420.723747,404.420013,-421.188995,119.807999,160.0,Quiet Sun,Atlas_60,eis_20201028_010513.data.h5,344.516014,464.324013,-501.188995,-341.188995
108,404,2020-11-01 00:20:13,B1.9,910.260809,-359.966307,858.008972,-293.196991,119.807999,160.0,Quiet Sun,Atlas_60,eis_20201101_002013.data.h5,798.104973,917.912971,-373.196991,-213.196991
113,404,2020-11-05 22:28:13,C1.0,-669.293825,-387.275648,-647.000977,-427.066986,119.807999,160.0,Quiet Sun,Atlas_60,eis_20201105_222813.data.h5,-706.904976,-587.096977,-507.066986,-347.066986
117,404,2020-11-15 21:48:10,B2.1,903.647959,-376.445872,860.130005,-348.355988,119.807999,160.0,Quiet Sun,Atlas_60,eis_20201115_214810.data.h5,800.226006,920.034004,-428.355988,-268.355988
119,404,2020-11-19 20:52:40,B2.0,507.115789,-569.342723,471.579987,-539.007019,119.807999,160.0,Quiet Sun,Atlas_60,eis_20201119_205240.data.h5,411.675987,531.483986,-619.007019,-459.007019
120,404,2020-11-25 02:43:10,C3.4,-855.220767,-299.035215,-878.393005,-322.335999,119.807999,160.0,Quiet Sun,Atlas_60,eis_20201125_024310.data.h5,-938.297005,-818.489006,-402.335999,-242.335999
145,404,2021-08-24 12:48:00,B3.2,-594.018315,201.509319,-636.726990,222.052994,119.807999,160.0,Quiet Sun,Atlas_60,eis_20210824_124800.data.h5,-696.630989,-576.822990,142.052994,302.052994
162,404,2021-11-16 11:53:05,B1.4,675.560222,404.897763,656.749023,335.759003,119.807999,160.0,Quiet Sun,Atlas_60,eis_20211116_115305.data.h5,596.845024,716.653023,255.759003,415.759003
236,404,2018-06-17 14:33:11,B1.2,-133.589558,57.955393,-173.951996,4.486040,119.807999,160.0,Quiet Sun,Atlas_60,eis_20180617_143311.data.h5,-233.855995,-114.047997,-75.513960,84.486040
252,403,2016-02-13 10:44:42,B8.5,419.562555,335.575594,401.136993,292.191010,119.807999,160.0,Quiet Sun,Atlas_30,eis_20160213_104442.data.h5,341.232994,461.040993,212.191010,372.191010
258,403,2016-02-29 04:03:37,B6.9,53.907844,-32.523403,66.003899,-10.387700,119.807999,160.0,Quiet Sun,Atlas_30,eis_20160229_040337.data.h5,6.099899,125.907898,-90.387700,69.612300
266,404,2016-04-19 18:47:20,B4.3,893.381910,248.330836,911.744995,191.507996,119.807999,160.0,Quiet Sun,Atlas_60,eis_20160419_184720.data.h5,851.840996,971.648994,111.507996,271.507996
267,404,2016-04-20 07:32:13,B4.7,914.970288,242.280243,951.931030,211.507996,119.807999,160.0,Quiet Sun,Atlas_60,eis_20160420_073213.data.h5,892.027031,1011.835030,131.507996,291.507996
273,404,2016-05-13 04:55:28,B3.1,576.772960,190.830221,611.351990,189.677002,119.807999,160.0,Quiet Sun,Atlas_60,eis_20160513_045528.data.h5,551.447990,671.255989,109.677002,269.677002
274,404,2016-05-14 07:07:19,B7.6,751.011981,172.858943,765.476990,170.865997,119.807999,160.0,Quiet Sun,Atlas_60,eis_20160514_070719.data.h5,705.572990,825.380989,90.865997,250.865997
275,404,2016-05-20 00:50:51,B2.6,-127.520618,-66.276031,-75.610298,-121.768997,119.807999,160.0,Quiet Sun,Atlas_60,eis_20160520_005051.data.h5,-135.514297,-15.706299,-201.768997,-41.768997
287,403,2016-07-20 02:37:43,C1.6,473.464941,-26.492045,477.135010,-47.881001,119.807999,160.0,Quiet Sun,Atlas_30,eis_20160720_023743.data.h5,417.231010,537.039009,-127.881001,32.118999
301,404,2016-09-27 12:25:27,B2.5,673.753284,-307.493219,680.591003,-342.140991,119.807999,160.0,Quiet Sun,Atlas_60,eis_20160927_122527.data.h5,620.687004,740.495003,-422.140991,-262.140991
303,404,2016-10-14 11:05:26,B9.4,869.102432,-250.921809,825.442993,-300.179993,119.807999,160.0,Quiet Sun,Atlas_60,eis_20161014_110526.data.h5,765.538994,885.346992,-380.179993,-220.179993
306,404,2016-11-30 14:07:02,C1.0,-665.139483,-133.800164,-693.880981,-166.505005,119.807999,160.0,Quiet Sun,Atlas_60,eis_20161130_140702.data.h5,-753.784981,-633.976982,-246.505005,-86.505005
321,404,2017-04-22 14:03:42,B2.1,-334.466036,292.084481,-308.917999,223.792007,119.807999,160.0,Quiet Sun,Atlas_60,eis_20170422_140342.data.h5,-368.821999,-249.014000,143.792007,303.792007
323,404,2017-05-28 00:23:17,B3.8,765.763238,242.883670,746.937988,163.712997,119.807999,160.0,Quiet Sun,Atlas_60,eis_20170528_002317.data.h5,687.033989,806.841988,83.712997,243.712997
325,403,2017-05-28 15:20:42,B3.0,835.359909,236.716175,816.056030,159.623001,119.807999,160.0,Quiet Sun,Atlas_30,eis_20170528_152042.data.h5,756.152031,875.960030,79.623001,239.623001
326,404,2017-05-29 10:48:25,B2.3,902.543356,225.152534,880.747986,155.914993,119.807999,160.0,Quiet Sun,Atlas_60,eis_20170529_104825.data.h5,820.843987,940.651985,75.914993,235.914993
394,404,2015-05-10 13:09:33,C2.2,-296.547806,270.977659,-250.339996,207.873001,119.807999,160.0,Quiet Sun,Atlas_60,eis_20150510_130933.data.h5,-310.243996,-190.435997,127.873001,287.873001
396,404,2015-06-21 02:08:34,M2.7,-246.412361,149.407455,-265.708008,214.897995,119.807999,160.0,Quiet Sun,Atlas_60,eis_20150621_020834.data.h5,-325.612007,-205.804008,134.897995,294.897995
420,404,2015-12-16 04:47:27,B7.0,6.081072,-279.083943,20.959499,-227.628006,119.807999,160.0,Quiet Sun,Atlas_60,eis_20151216_044727.data.h5,-38.944500,80.863499,-307.628006,-147.628006
424,403,2014-01-08 12:01:32,C3.6,190.249605,-91.313893,133.009995,-93.351601,119.807999,160.0,Quiet Sun,Atlas_30,eis_20140108_120132.data.h5,73.105995,192.913994,-173.351601,-13.351601
426,403,2014-01-11 12:30:27,C6.5,692.625075,-128.321860,635.137024,-108.768997,119.807999,160.0,Quiet Sun,Atlas_30,eis_20140111_123027.data.h5,575.233025,695.041023,-188.768997,-28.768997
462,404,2014-08-07 03:09:13,B7.7,297.359239,-392.658056,289.589996,-439.279999,119.807999,160.0,Quiet Sun,Atlas_60,eis_20140807_030913.data.h5,229.685997,349.493996,-519.279999,-359.279999
465,403,2014-08-15 02:27:25,B6.2,-466.391154,175.757863,-456.462006,117.406998,119.807999,160.0,Quiet Sun,Atlas_30,eis_20140815_022725.data.h5,-516.366005,-396.558006,37.406998,197.406998
513,404,2011-03-19 15:34:09,B2.7,320.211861,296.903165,356.609009,331.433014,119.807999,160.0,Quiet Sun,Atlas_60,eis_20110319_153409.data.h5,296.705009,416.513008,251.433014,411.433014
517,404,2011-04-11 13:23:00,B7.2,-502.142377,297.172908,-534.364990,301.614990,119.807999,160.0,Quiet Sun,Atlas_60,eis_20110411_132300.data.h5,-594.268990,-474.460991,221.614990,381.614990
519,404,2011-04-15 02:30:26,B8.8,222.237960,317.038580,198.867996,304.395996,119.807999,160.0,Quiet Sun,Atlas_60,eis_20110415_023026.data.h5,138.963997,258.771996,224.395996,384.395996
527,404,2011-07-11 00:29:26,B3.6,214.474807,-361.715296,236.643997,-405.817993,119.807999,160.0,Quiet Sun,Atlas_60,eis_20110711_002926.data.h5,176.739998,296.547997,-485.817993,-325.817993
562,403,2013-01-12 19:08:20,C3.9,-286.555073,141.533609,-323.786011,195.296997,119.807999,160.0,Quiet Sun,Atlas_30,eis_20130112_190820.data.h5,-383.690010,-263.882011,115.296997,275.296997
605,404,2013-08-02 10:48:10,B9.7,191.178621,-343.986357,140.580994,-389.441986,119.807999,160.0,Quiet Sun,Atlas_60,eis_20130802_104810.data.h5,80.676994,200.484993,-469.441986,-309.441986
631,403,2013-12-28 10:38:41,C1.2,491.649901,-295.964737,439.647003,-239.041000,119.807999,160.0,Quiet Sun,Atlas_30,eis_20131228_103841.data.h5,379.743004,499.551003,-319.041000,-159.041000
663,404,2012-06-13 11:05:35,M1.2,-323.556296,-315.198557,-345.769989,-333.746002,119.807999,160.0,Quiet Sun,Atlas_60,eis_20120613_110535.data.h5,-405.673988,-285.865990,-413.746002,-253.746002

In [26]:

# Define the path pattern for CSV files
path_pattern = '/Users/andysh.to/Script/Python_Script/eis_flare_project_esa_computer/flare_dfs/filtered_flares_by_date_*.csv'

# Get list of all matching CSV files
flare_csv_files = glob.glob(path_pattern)

# Read and concatenate all CSV files into one dataframe
dfs = []
for file in flare_csv_files:
    df = pd.read_csv(file)
    dfs.append(df)
    
# Combine all dataframes
flare_df = pd.concat(dfs, ignore_index=True)

# Optional: Sort by date if there's a date column
# combined_df = combined_df.sort_values('date_column_name')

In [29]:
# Merge filtered_df with flare_df based on matching times
# First rename the column in flare_df to match filtered_df for merging
flare_df_renamed = flare_df.rename(columns={'EIS flare times': 'flare times'})

# Merge the dataframes on 'flare times' column
filtered_df = pd.merge(filtered_df, 
                      flare_df_renamed[['flare times', 'Start Time', 'Peak Time', 'End Time']], 
                      on='flare times',
                      how='left')

# Display the result
# Rename 'flare times' to 'eis filename time' and display the result
filtered_df = filtered_df.rename(columns={'flare times': 'eis filename time'})
filtered_df

,study ID,eis filename time,GOES class,hpc x,hpc y,EIS xcen,EIS ycen,EIS fovx,EIS fovy,target,...,EIS xmin,EIS xmax,EIS ymin,EIS ymax,Start Time_x,Peak Time_x,End Time_x,Start Time_y,Peak Time_y,End Time_y
0,404,2023-02-09 12:20:50,C8.4,226.114515,592.661631,236.604996,583.794006,119.807999,160.0,Quiet Sun,...,176.700996,296.508995,503.794006,663.794006,2023-02-09 12:03:00.000,2023-02-09 12:20:00.000,2023-02-09 12:43:00.000,2023-02-09 12:03:00.000,2023-02-09 12:20:00.000,2023-02-09 12:43:00.000
1,404,2023-04-13 00:07:02,C4.0,40.691096,-232.021582,-14.057000,-286.865997,119.807999,160.0,Quiet Sun,...,-73.960999,45.846999,-366.865997,-206.865997,2023-04-13 00:24:00.000,2023-04-13 00:53:00.000,2023-04-13 01:03:00.000,2023-04-13 00:24:00.000,2023-04-13 00:53:00.000,2023-04-13 01:03:00.000
2,404,2023-05-10 14:07:44,M2.2,670.942131,263.190417,613.252991,242.753006,119.807999,160.0,Quiet Sun,...,553.348991,673.156990,162.753006,322.753006,2023-05-10 14:11:00.000,2023-05-10 14:21:00.000,2023-05-10 14:33:00.000,2023-05-10 14:11:00.000,2023-05-10 14:21:00.000,2023-05-10 14:33:00.000
3,404,2023-05-21 23:55:18,C8.2,-514.125840,323.252654,-561.046997,304.997009,119.807999,160.0,Quiet Sun,...,-620.950996,-501.142998,224.997009,384.997009,2023-05-22 00:55:00.000,2023-05-22 01:08:00.000,2023-05-22 01:18:00.000,2023-05-22 00:55:00.000,2023-05-22 01:08:00.000,2023-05-22 01:18:00.000
4,404,2023-05-23 07:01:47,C2.3,-279.806431,328.104618,-329.031006,307.315002,119.807999,160.0,Quiet Sun,...,-388.935005,-269.127007,227.315002,387.315002,2023-05-23 06:55:00.000,2023-05-23 07:05:00.000,2023-05-23 07:09:00.000,2023-05-23 06:55:00.000,2023-05-23 07:05:00.000,2023-05-23 07:09:00.000
5,404,2023-05-24 19:12:41,C5.1,3.320805,366.961252,-15.982300,298.131012,119.807999,160.0,Quiet Sun,...,-75.886299,43.921700,218.131012,378.131012,2023-05-24 19:03:00.000,2023-05-24 19:10:00.000,2023-05-24 19:18:00.000,2023-05-24 19:03:00.000,2023-05-24 19:10:00.000,2023-05-24 19:18:00.000
6,404,2022-04-21 12:50:13,C5.4,-318.983796,321.250288,-304.621002,345.454987,119.807999,160.0,Quiet Sun,...,-364.525002,-244.717003,265.454987,425.454987,2022-04-21 12:47:00.000,2022-04-21 12:55:00.000,2022-04-21 13:01:00.000,2022-04-21 12:47:00.000,2022-04-21 12:55:00.000,2022-04-21 13:01:00.000
7,404,2022-04-28 23:41:08,C1.2,908.003901,230.528214,868.919006,268.834015,119.807999,160.0,Quiet Sun,...,809.015007,928.823006,188.834015,348.834015,2022-04-28 23:45:00.000,2022-04-28 23:52:00.000,2022-04-29 00:05:00.000,2022-04-28 23:45:00.000,2022-04-28 23:52:00.000,2022-04-29 00:05:00.000
8,404,2022-05-26 12:24:42,C1.6,844.022005,203.078171,806.900024,179.438004,119.807999,160.0,Quiet Sun,...,746.996025,866.804024,99.438004,259.438004,2022-05-26 13:08:00.000,2022-05-26 13:19:00.000,2022-05-26 13:25:00.000,2022-05-26 13:08:00.000,2022-05-26 13:19:00.000,2022-05-26 13:25:00.000
9,404,2022-07-24 14:21:13,B4.9,784.446421,125.492067,741.793030,134.914993,119.807999,160.0,Quiet Sun,...,681.889030,801.697029,54.914993,214.914993,2022-07-24 14:57:00.000,2022-07-24 15:02:00.000,2022-07-24 15:06:00.000,2022-07-24 14:57:00.000,2022-07-24 15:02:00.000,2022-07-24 15:06:00.000
10,404,2022-07-29 14:01:13,B2.3,-513.531629,256.119982,-518.026978,226.729004,119.807999,160.0,Quiet Sun,...,-577.930977,-458.122978,146.729004,306.729004,2022-07-29 13:52:00.000,2022-07-29 13:57:00.000,2022-07-29 14:05:00.000,2022-07-29 13:52:00.000,2022-07-29 13:57:00.000,2022-07-29 14:05:00.000
11,404,2022-10-02 11:03:20,C2.4,-836.228440,335.517527,-792.304016,327.319000,119.807999,160.0,Quiet Sun,...,-852.208015,-732.400017,247.319000,407.319000,2022-10-02 11:30:00.000,2022-10-02 11:39:00.000,2022-10-02 11:44:00.000,2022-10-02 11:30:00.000,2022-10-02 11:39:00.000,2022-10-02 11:44:00.000
12,404,2022-10-02 11:03:20,C3.0,-836.834387,333.118342,-792.304016,327.319000,119.807999,160.0,Quiet Sun,...,-852.208015,-732.400017,247.319000,407.319000,2022-10-02 11:30:00.000,2022-10-02 11:39:00.000,2022-10-02 11:44:00.000,2022-10-02 11:30:00.000,2022-10-02 11:39:00.000,2022-10-02 11:44:00.000
13,404,2020-04-09 08:38:43,B1.6,717.100898,514.454679,675.604004,499.929993,119.807999,160.0,Quiet Sun,...,615.700005,735.508003,419.929993,579.929993,2020-04-09 01:31:00.000,2020-04-09 09:32:00.000,2020-04-09 09:18:00.000,2020-04-09 01:31:00.000,2020-04-09 09:32:00.000,2020-04-09 09:18:00.000
14,404,2020-10-27 15:50:40,B7.9,367.229246,-429.764362,331.200989,-444.820007,119.807999,160.0,Quiet Sun,...,271.296989,391.104988,-524.820007,-364.820007,2020-10-27 15:43:00.000,2020-10-27 15:54:00.000,2020-10-27 16:01:00.000,2020-10-27 15:43:00.000,2020-10-27 15:54:00.000,2020-10-27 16:01:00.000
15,404,2020-10-28 01:05:13,C1.1,461.896696,-420.723747,404.420013,-421.188995,119.807999,160.0,Quiet Sun,...,344.516014,464.324013,-501.188995,-341.188995,2020-10-28 02:00:00.000,2020-10-28 02:11:00.000,2020-10-28 02:16:00.000,2020-10-28 02:00:00.000,2020-10-28 02:11:00.000,2020-10-28 02:16:00.000
16,404,2020-11-01 00:20:13,B1.9,910.260809,-359.966307,858.008972,-293.196991,119.807999,160.0,Quiet Sun,...,798.104973,917.912971,-373.196991,-213.196991,2020-11-01 00:45:00.000,2020-11-01 00:54:00.000,2020-11-01 01:00:00.000,2020-11-01 00:45:00.000,2020-11-01 00:54:00.000,2020-11-01 01:00:00.000
17,404,2020-11-05 22:28:13,C1.0,-669.293825,-387.275648,-647.000977,-427.066986,119.807999,160.0,Quiet Sun,...,-706.904976,-587.096977,-507.066986,-347.066986,2020-11-05 22:18:00.000,2020-11-05 22:23:00.000,2020-11-05 22:33:00.000,2020-11-05 22:18:00.000,2020-11-05 22:23:00.000,2020-11-05 22:33:00.000
18,404,2020-11-15 21:48:10,B2.1,903.647959,-376.445872,860.130005,-348.355988,119.807999,160.0,Quiet Sun,...,800.226006,920.034004,-428.355988,-268.355988,2020-11-15 22:28:00.000,2020-11-15 22:37:00.000,2020-11-15 22:43:00.000,2020-11-15 22:28:00.000,2020-11-15 22:37:00.000,2020-11-15 22:43:00.000
19,404,2020-11-19 20:52:40,B2.0,507.115789,-569.342723,471.579987,-539.007019,119.807999,160.0,Quiet Sun,...,411.675987,531.483986,-619.007019,-459.007019,2020-11-19 20:38:00.000,2020-11-19 21:06:00.000,2020-11-19 21:19:00.000,2020-11-19 20:38:00.000,2020-11-19 21:06:00.000,2020-11-19 21:19:00.000
20,404,2020-11-25 02:43:10,C3.4,-855.220767,-299.035215,-878.393005,-322.335999,119.807999,160.0,Quiet Sun,...,-938.297005,-818.489006,-402.335999,-242.335999,2020-11-25 03:47:00.000,2020-11-25 04:02:00.000,2020-11-25 04:21:00.000,2020-11-25 03:47:00.000,2020-11-25 04:02:00.000,2020-11-25 04:21:00.000
21,404,2021-08-24 12:48:00,B3.2,-594.018315,201.509319,-636.726990,222.052994,119.807999,160.0,Quiet Sun,...,-696.630989,-576.822990,142.052994,302.052994,2021-08-24 13:35:00.000,2021-08-24 13:45:00.000,2021-08-24 13:49:00.000,2021-08-24 13:35:00.000,2021-08-24 13:45:00.000,2021-08-24 13:49:00.000
22,404,2021-11-16 11:53:05,B1.4,675.560222,404.897763,656.749023,335.759003,119.807999,160.0,Quiet Sun,...,596.845024,716.653023,255.759003,415.759003,2021-11-16 12:07:00.000,2021-11-16 12:18:00.000,2021-11-16 12:23:00.000,2021-11-16 12:07:00.000,2021-11-16 12:18:00.000,2021-11-16 12:23:00.000
23,404,2018-06-17 14:33:11,B1.2,-133.589558,57.955393,-173.951996,4.486040,119.807999,160.0,Quiet Sun,...,-233.855995,-114.047997,-75.513960,84.486040,2018-06-17 13:12:00.000,2018-06-17 14:29:00.000,2018-06-17 15:02:00.000,2018-06-17 13:12:00.000,2018-06-17 14:29:00.000,2018-06-17 15:02:00.000
24,403,2016-02-13 10:44:42,B8.5,419.562555,335.575594,401.136993,292.191010,119.807999,160.0,Quiet Sun,...,341.232994,461.040993,212.191010,372.191010,2016-02-13 10:58:00.000,2016-02-13 11:01:00.000,2016-02-13 11:06:00.000,2016-02-13 10:58:00.000,2016-02-13 11:01:00.000,2016-02-13 11:06:00.000
25,403,2016-02-29 04:03:37,B6.9,53.907844,-32.523403,66.003899,-10.387700,119.807999,160.0,Quiet Sun,...,6.099899,125.907898,-90.387700,69.612300,2016-02-29 04:19:00.000,2016-02-29 04:30:00.000,2016-02-29 04:41:00.000,2016-02-29 04:19:00.000,2016-02-29 04:30:00.000,2016-02-29 04:41:00.000
26,404,2016-04-19 18:47:20,B4.3,893.381910,248.330836,911.744995,191.507996,119.807999,160.0,Quiet Sun,...,851.840996,971.648994,111.507996,271.507996,2016-04-19 19:26:00.000,2016-04-19 19:34:00.000,2016-04-19 19:42:00.000,2016-04-19 19:26:00.000,2016-04-19 19:34:00.000,2016-04-19 19:42:00.000
27,404,2016-04-20 07:32:13,B4.7,914.970288,242.280243,951.931030,211.507996,119.807999,160.0,Quiet Sun,...,892.027031,1011.835030,131.507996,291.507996,2016-04-20 07:31:00.000,2016-04-20 07:41:00.000,2016-04-20 07:46:00.000,2016-04-20 07:31:00.000,2016-04-20 07:41:00.000,2016-04-20 07:46:00.000
28,404,2016-05-13 04:55:28,B3.1,576.772960,190.830221,611.351990,189.677002,119.807999,160.0,Quiet Sun,...,551.447990,671.255989,109.677002,269.677002,2016-05-13 05:08:00.000,2016-05-13 05:09:00.000,2016-05-13 05:11:00.000,2016-05-13 05:08:00.000,2016-05-13 05:09:00.000,2016-05-13 05:11:00.000
29,404,2016-05-14 07:07:19,B7.6,751.011981,172.858943,765.476990,170.865997,119.807999,160.0,Quiet Sun,...,705.572990,825.380989,90.865997,250.865997,2016-05-14 07:44:00.000,2016-05-14 07:52:00.000,2016-05-14 07:58:00.000,2016-05-14 07:44:00.000,2016-05-14 07:52:00.000,2016-05-14 07:58:00.000
30,404,2016-05-20 00:50:51,B2.6,-127.520618,-66.276031,-75.610298,-121.768997,119.807999,160.0,Quiet Sun,...,-135.514297,-15.706299,-201.768997,-41.768997,2016-05-20 00:55:00.000,2016-05-20 00:59:00.000,2016-05-20 01:02:00.000,2016-05-20 00:55:00.000,2016-05-20 00:59:00.000,2016-05-20 01:02:00.000
31,403,2016-07-20 02:37:43,C1.6,473.464941,-26.492045,477.135010,-47.881001,119.807999,160.0,Quiet Sun,...,417.231010,537.039009,-127.881001,32.118999,2016-07-20 02:40:00.000,2016-07-20 02:49:00.000,2016-07-20 02:59:00.000,2016-07-20 02:40:00.000,2016-07-20 02:49:00.000,2016-07-20 02:59:00.000
32,404,2016-09-27 12:25:27,B2.5,673.753284,-307.493219,680.591003,-342.140991,119.807999,160.0,Quiet Sun,...,620.687004,740.495003,-422.140991,-262.140991,2016-09-27 12:49:00.000,2016-09-27 12:54:00.000,2016-09-27 12:58:00.000,2016-09-27 12:49:00.000,2016-09-27 12:54:00.000,2016-09-27 12:58:00.000
33,404,2016-10-14 11:05:26,B9.4,869.102432,-250.921809,825.442993,-300.179993,119.807999,160.0,Quiet Sun,...,765.538994,885.346992,-380.179993,-220.179993,2016-10-14 11:19:00.000,2016-10-14 11:26:00.000,2016-10-14 11:33:00.000,2016-10-14 11:19:00.000,2016-10-14 11:26:00.000,2016-10-14 11:33:00.000
34,404,2016-11-30 14:07:02,C1.0,-665.139483,-133.800164,-693.880981,-166.505005,119.807999,160.0,Quiet Sun,...,-753.784981,-633.976982,-246.505005,-86.505005,2016-11-30 15:00:00.000,2016-11-30 15:07:00.000,2016-11-30 15:11:00.000,2016-11-30 15:00:00.000,2016-11-30 15:07:00.000,2016-11-30 15:11:00.000
35,404,2017-04-22 14:03:42,B2.1,-334.466036,292.084481,-308.917999,223.792007,119.807999,160.0,Quiet Sun,...,-368.821999,-249.014000,143.792007,303.792007,2017-04-22 14:52:00.000,2017-04-22 14:58:00.000,2017-04-22 15:01:00.000,2017-04-22 14:52:00.000,2017-04-22 14:58:00.000,2017-04-22 15:01:00.000
36,404,2017-05-28 00:23:17,B3.8,765.763238,242.883670,746.937988,163.712997,119.807999,160.0,Quiet Sun,...,687.033989,806.841988,83.712997,243.712997,2017-05-28 00:55:00.000,2017-05-28 01:00:00.000,2017-05-28 01:03:00.000,2017-05-28 00:55:00.000,2017-05-28 01:00:00.000,2017-05-28 01:03:00.000
37,403,2017-05-28 15:20:42,B3.0,835.359909,236.716175,816.056030,159.623001,119.807999,160.0,Quiet Sun,...,756.152031,875.960030,79.623001,239.623001,2017-05-28 15:42:00.000,2017-05-28 15:52:00.000,2017-05-28 15:57:00.000,2017-05-28 15:42:00.000,2017-05-28 15:52:00.000,2017-05-28 15:57:00.000
38,404,2017-05-29 10:48:25,B2.3,902.543356,225.152534,880.747986,155.914993,119.807999,160.0,Quiet Sun,...,820.843987,940.651985,75.914993,235.914993,2017-05-29 11:35:00.000,2017-05-29 11:41:00.000,2017-05-29 11:47:00.000,2017-05-29 11:35:00.000,2017-05-29 11:41:00.000,2017-05-29 11:47:00.000
39,404,2015-05-10 13:09:33,C2.2,-296.547806,270.977659,-250.339996,207.873001,119.807999,160.0,Quiet Sun,...,-310.243996,-190.435997,127.873001,287.873001,2015-05-10 12:45:00.000,2015-05-10 13:03:00.000,2015-05-10 13:23:00.000,2015-05-10 12:45:00.000,2015-05-10 13:03:00.000,2015-05-10 13:23:00.000
40,404,2015-06-21 02:08:34,M2.7,-246.412361,149.407455,-265.708008,214.897995,119.807999,160.0,Quiet Sun,...,-325.612007,-205.804008,134.897995,294.897995,2015-06-21 02:04:00.000,2015-06-21 02:34:00.000,2015-06-21 03:11:00.000,2015-06-21 02:04:00.000,2015-06-21 02:34:00.000,2015-06-21 03:11:00.000
41,404,2015-12-16 04:47:27,B7.0,6.081072,-279.083943,20.959499,-227.628006,119.807999,160.0,Quiet Sun,...,-38.944500,80.863499,-307.628006,-147.628006,2015-12-16 05:44:00.000,2015-12-16 05:48:00.000,2015-12-16 05:53:00.000,2015-12-16 05:44:00.000,2015-12-16 05:48:00.000,2015-12-16 05:53:00.000
42,403,2014-01-08 12:01:32,C3.6,190.249605,-91.313893,133.009995,-93.351601,119.807999,160.0,Quiet Sun,...,73.105995,192.913994,-173.351601,-13.351601,2014-01-08 11:56:00.000,2014-01-08 12:04:00.000,2014-01-08 12:17:00.000,2014-01-08 11:56:00.000,2014-01-08 12:04:00.000,2014-01-08 12:17:00.000
43,403,2014-01-11 12:30:27,C6.5,692.625075,-128.321860,635.137024,-108.768997,119.807999,160.0,Quiet Sun,...,575.233025,695.041023,-188.768997,-28.768997,2014-01-11 13:00:00.000,2014-01-11 13:10:00.000,2014-01-11 13:22:00.000,2014-01-11 13:00:00.000,2014-01-11 13:10:00.000,2014-01-11 13:22:00.000
44,404,2014-08-07 03:09:13,B7.7,297.359239,-392.658056,289.589996,-439.279999,119.807999,160.0,Quiet Sun,...,229.685997,349.493996,-519.279999,-359.279999,2014-08-07 03:05:00.000,2014-08-07 03:09:00.000,2014-08-07 03:17:00.000,2014-08-07 03:05:00.000,2014-08-07 03:09:00.000,2014-08-07 03:17:00.000
45,403,2014-08-15 02:27:25,B6.2,-466.391154,175.757863,-456.462006,117.406998,119.807999,160.0,Quiet Sun,...,-516.366005,-396.558006,37.406998,197.406998,2014-08-15 02:34:00.000,2014-08-15 02:39:00.000,2014-08-15 02:47:00.000,2014-08-15 02:34:00.000,2014-08-15 02:39:00.000,2014-08-15 02:47:00.000
46,404,2011-03-19 15:34:09,B2.7,320.211861,296.903165,356.609009,331.433014,119.807999,160.0,Quiet Sun,...,296.705009,416.513008,251.433014,411.433014,2011-03-19 16:21:00.000,2011-03-19 16:34:00.000,2011-03-19 16:52:00.000,2011-03-19 16:21:00.000,2011-03-19 16:34:00.000,2011-03-19 16:52:00.000
47,404,2011-04-11 13:23:00,B7.2,-502.142377,297.172908,-534.364990,301.614990,119.807999,160.0,Quiet Sun,...,-594.268990,-474.460991,221.614990,381.614990,2011-04-11 12:49:00.000,2011-04-11 13:10:00.000,2011-04-11 13:26:00.000,2011-04-11 12:49:00.000,2011-04-11 13:10:00.000,2011-04-11 13:26:00.000
48,404,2011-04-15 02:30:26,B8.8,222.237960,317.038580,198.867996,304.395996,119.807999,160.0,Quiet Sun,...,138.963997,258.771996,224.395996,384.395996,2011-04-15 02:43:00.000,2011-04-15 02:47:00.000,2011-04-15 02:52:00.000,2011-04-15 02:43:00.000,2011-04-15 02:47:00.000,2011-04-15 02:52:00.000
49,404,2011-07-11 00:29:26,B3.6,214.474807,-361.715296,236.643997,-405.817993,119.807999,160.0,Quiet Sun,...,176.739998,296.547997,-485.817993,-325.817993,2011-07-11 01:12:00.000,2011-07-11 01:17:00.000,2011-07-11 01:20:00.000,2011-07-11 01:12:00.000,2011-07-11 01:17:00.000,2011-07-11 01:20:00.000
50,403,2013-01-12 19:08:20,C3.9,-286.555073,141.533609,-323.786011,195.296997,119.807999,160.0,Quiet Sun,...,-383.690010,-263.882011,115.296997,275.296997,2013-01-12 19:26:00.000,2013-01-12 19:33:00.000,2013-01-12 19:38:00.000,2013-01-12 19:26:00.000,2013-01-12 19:33:00.000,2013-01-12 19:38:00.000
51,404,2013-08-02 10:48:10,B9.7,191.178621,-343.986357,140.580994,-389.441986,119.807999,160.0,Quiet Sun,...,80.676994,200.484993,-469.441986,-309.441986,2013-08-02 11:08:00.000,2013-08-02 11:15:00.000,2013-08-02 11:24:00.000,2013-08-02 11:08:00.000,2013-08-02 11:15:00.000,2013-08-02 11:24:00.000
52,403,2013-12-28 10:38:41,C1.2,491.649901,-295.964737,439.647003,-239.041000,119.807999,160.0,Quiet Sun,...,379.743004,499.551003,-319.041000,-159.041000,2013-12-28 11:00:00.000,2013-12-28 11:18:00.000,2013-12-28 11:32:00.000,2013-12-28 11:00:00.000,2013-12-28 11:18:00.000,2013-12-28 11:32:00.000
53,404,2012-06-13 11:05:35,M1.2,-323.556296,-315.198557,-345.769989,-333.746002,119.807999,160.0,Quiet Sun,...,-405.673988,-285.865990,-413.746002,-253.746002,2012-06-13 11:29:00.000,2012-06-13 13:17:00.000,2012-06-13 14:31:00.000,2012-06-13 11:29:00.000,2012-06-13 13:17:00.000,2012-06-13 14:31:00.000

In [30]:
# Export the filtered dataframe to CSV
filtered_df.to_csv('filtered_dfs/atlas_flares.csv', index=False)

In [32]:
# Read the filtered flares CSV file
import pandas as pd
filtered_df = pd.read_csv('filtered_dfs/atlas_flares.csv')

In [33]:
filtered_df

,study ID,eis filename time,GOES class,hpc x,hpc y,EIS xcen,EIS ycen,EIS fovx,EIS fovy,target,...,EIS xmin,EIS xmax,EIS ymin,EIS ymax,Start Time_x,Peak Time_x,End Time_x,Start Time_y,Peak Time_y,End Time_y
0,404,2023-02-09 12:20:50,C8.4,226.114515,592.661631,236.604996,583.794006,119.807999,160.0,Quiet Sun,...,176.700996,296.508995,503.794006,663.794006,2023-02-09 12:03:00.000,2023-02-09 12:20:00.000,2023-02-09 12:43:00.000,2023-02-09 12:03:00.000,2023-02-09 12:20:00.000,2023-02-09 12:43:00.000
1,404,2023-04-13 00:07:02,C4.0,40.691096,-232.021582,-14.057000,-286.865997,119.807999,160.0,Quiet Sun,...,-73.960999,45.846999,-366.865997,-206.865997,2023-04-13 00:24:00.000,2023-04-13 00:53:00.000,2023-04-13 01:03:00.000,2023-04-13 00:24:00.000,2023-04-13 00:53:00.000,2023-04-13 01:03:00.000
2,404,2023-05-10 14:07:44,M2.2,670.942131,263.190417,613.252991,242.753006,119.807999,160.0,Quiet Sun,...,553.348991,673.156990,162.753006,322.753006,2023-05-10 14:11:00.000,2023-05-10 14:21:00.000,2023-05-10 14:33:00.000,2023-05-10 14:11:00.000,2023-05-10 14:21:00.000,2023-05-10 14:33:00.000
3,404,2023-05-21 23:55:18,C8.2,-514.125840,323.252654,-561.046997,304.997009,119.807999,160.0,Quiet Sun,...,-620.950996,-501.142998,224.997009,384.997009,2023-05-22 00:55:00.000,2023-05-22 01:08:00.000,2023-05-22 01:18:00.000,2023-05-22 00:55:00.000,2023-05-22 01:08:00.000,2023-05-22 01:18:00.000
4,404,2023-05-23 07:01:47,C2.3,-279.806431,328.104618,-329.031006,307.315002,119.807999,160.0,Quiet Sun,...,-388.935005,-269.127007,227.315002,387.315002,2023-05-23 06:55:00.000,2023-05-23 07:05:00.000,2023-05-23 07:09:00.000,2023-05-23 06:55:00.000,2023-05-23 07:05:00.000,2023-05-23 07:09:00.000
5,404,2023-05-24 19:12:41,C5.1,3.320805,366.961252,-15.982300,298.131012,119.807999,160.0,Quiet Sun,...,-75.886299,43.921700,218.131012,378.131012,2023-05-24 19:03:00.000,2023-05-24 19:10:00.000,2023-05-24 19:18:00.000,2023-05-24 19:03:00.000,2023-05-24 19:10:00.000,2023-05-24 19:18:00.000
6,404,2022-04-21 12:50:13,C5.4,-318.983796,321.250288,-304.621002,345.454987,119.807999,160.0,Quiet Sun,...,-364.525002,-244.717003,265.454987,425.454987,2022-04-21 12:47:00.000,2022-04-21 12:55:00.000,2022-04-21 13:01:00.000,2022-04-21 12:47:00.000,2022-04-21 12:55:00.000,2022-04-21 13:01:00.000
7,404,2022-04-28 23:41:08,C1.2,908.003901,230.528214,868.919006,268.834015,119.807999,160.0,Quiet Sun,...,809.015007,928.823006,188.834015,348.834015,2022-04-28 23:45:00.000,2022-04-28 23:52:00.000,2022-04-29 00:05:00.000,2022-04-28 23:45:00.000,2022-04-28 23:52:00.000,2022-04-29 00:05:00.000
8,404,2022-05-26 12:24:42,C1.6,844.022005,203.078171,806.900024,179.438004,119.807999,160.0,Quiet Sun,...,746.996025,866.804024,99.438004,259.438004,2022-05-26 13:08:00.000,2022-05-26 13:19:00.000,2022-05-26 13:25:00.000,2022-05-26 13:08:00.000,2022-05-26 13:19:00.000,2022-05-26 13:25:00.000
9,404,2022-07-24 14:21:13,B4.9,784.446421,125.492067,741.793030,134.914993,119.807999,160.0,Quiet Sun,...,681.889030,801.697029,54.914993,214.914993,2022-07-24 14:57:00.000,2022-07-24 15:02:00.000,2022-07-24 15:06:00.000,2022-07-24 14:57:00.000,2022-07-24 15:02:00.000,2022-07-24 15:06:00.000
10,404,2022-07-29 14:01:13,B2.3,-513.531629,256.119982,-518.026978,226.729004,119.807999,160.0,Quiet Sun,...,-577.930977,-458.122978,146.729004,306.729004,2022-07-29 13:52:00.000,2022-07-29 13:57:00.000,2022-07-29 14:05:00.000,2022-07-29 13:52:00.000,2022-07-29 13:57:00.000,2022-07-29 14:05:00.000
11,404,2022-10-02 11:03:20,C2.4,-836.228440,335.517527,-792.304016,327.319000,119.807999,160.0,Quiet Sun,...,-852.208015,-732.400017,247.319000,407.319000,2022-10-02 11:30:00.000,2022-10-02 11:39:00.000,2022-10-02 11:44:00.000,2022-10-02 11:30:00.000,2022-10-02 11:39:00.000,2022-10-02 11:44:00.000
12,404,2022-10-02 11:03:20,C3.0,-836.834387,333.118342,-792.304016,327.319000,119.807999,160.0,Quiet Sun,...,-852.208015,-732.400017,247.319000,407.319000,2022-10-02 11:30:00.000,2022-10-02 11:39:00.000,2022-10-02 11:44:00.000,2022-10-02 11:30:00.000,2022-10-02 11:39:00.000,2022-10-02 11:44:00.000
13,404,2020-04-09 08:38:43,B1.6,717.100898,514.454679,675.604004,499.929993,119.807999,160.0,Quiet Sun,...,615.700005,735.508003,419.929993,579.929993,2020-04-09 01:31:00.000,2020-04-09 09:32:00.000,2020-04-09 09:18:00.000,2020-04-09 01:31:00.000,2020-04-09 09:32:00.000,2020-04-09 09:18:00.000
14,404,2020-10-27 15:50:40,B7.9,367.229246,-429.764362,331.200989,-444.820007,119.807999,160.0,Quiet Sun,...,271.296989,391.104988,-524.820007,-364.820007,2020-10-27 15:43:00.000,2020-10-27 15:54:00.000,2020-10-27 16:01:00.000,2020-10-27 15:43:00.000,2020-10-27 15:54:00.000,2020-10-27 16:01:00.000
15,404,2020-10-28 01:05:13,C1.1,461.896696,-420.723747,404.420013,-421.188995,119.807999,160.0,Quiet Sun,...,344.516014,464.324013,-501.188995,-341.188995,2020-10-28 02:00:00.000,2020-10-28 02:11:00.000,2020-10-28 02:16:00.000,2020-10-28 02:00:00.000,2020-10-28 02:11:00.000,2020-10-28 02:16:00.000
16,404,2020-11-01 00:20:13,B1.9,910.260809,-359.966307,858.008972,-293.196991,119.807999,160.0,Quiet Sun,...,798.104973,917.912971,-373.196991,-213.196991,2020-11-01 00:45:00.000,2020-11-01 00:54:00.000,2020-11-01 01:00:00.000,2020-11-01 00:45:00.000,2020-11-01 00:54:00.000,2020-11-01 01:00:00.000
17,404,2020-11-05 22:28:13,C1.0,-669.293825,-387.275648,-647.000977,-427.066986,119.807999,160.0,Quiet Sun,...,-706.904976,-587.096977,-507.066986,-347.066986,2020-11-05 22:18:00.000,2020-11-05 22:23:00.000,2020-11-05 22:33:00.000,2020-11-05 22:18:00.000,2020-11-05 22:23:00.000,2020-11-05 22:33:00.000
18,404,2020-11-15 21:48:10,B2.1,903.647959,-376.445872,860.130005,-348.355988,119.807999,160.0,Quiet Sun,...,800.226006,920.034004,-428.355988,-268.355988,2020-11-15 22:28:00.000,2020-11-15 22:37:00.000,2020-11-15 22:43:00.000,2020-11-15 22:28:00.000,2020-11-15 22:37:00.000,2020-11-15 22:43:00.000
19,404,2020-11-19 20:52:40,B2.0,507.115789,-569.342723,471.579987,-539.007019,119.807999,160.0,Quiet Sun,...,411.675987,531.483986,-619.007019,-459.007019,2020-11-19 20:38:00.000,2020-11-19 21:06:00.000,2020-11-19 21:19:00.000,2020-11-19 20:38:00.000,2020-11-19 21:06:00.000,2020-11-19 21:19:00.000
20,404,2020-11-25 02:43:10,C3.4,-855.220767,-299.035215,-878.393005,-322.335999,119.807999,160.0,Quiet Sun,...,-938.297005,-818.489006,-402.335999,-242.335999,2020-11-25 03:47:00.000,2020-11-25 04:02:00.000,2020-11-25 04:21:00.000,2020-11-25 03:47:00.000,2020-11-25 04:02:00.000,2020-11-25 04:21:00.000
21,404,2021-08-24 12:48:00,B3.2,-594.018315,201.509319,-636.726990,222.052994,119.807999,160.0,Quiet Sun,...,-696.630989,-576.822990,142.052994,302.052994,2021-08-24 13:35:00.000,2021-08-24 13:45:00.000,2021-08-24 13:49:00.000,2021-08-24 13:35:00.000,2021-08-24 13:45:00.000,2021-08-24 13:49:00.000
22,404,2021-11-16 11:53:05,B1.4,675.560222,404.897763,656.749023,335.759003,119.807999,160.0,Quiet Sun,...,596.845024,716.653023,255.759003,415.759003,2021-11-16 12:07:00.000,2021-11-16 12:18:00.000,2021-11-16 12:23:00.000,2021-11-16 12:07:00.000,2021-11-16 12:18:00.000,2021-11-16 12:23:00.000
23,404,2018-06-17 14:33:11,B1.2,-133.589558,57.955393,-173.951996,4.486040,119.807999,160.0,Quiet Sun,...,-233.855995,-114.047997,-75.513960,84.486040,2018-06-17 13:12:00.000,2018-06-17 14:29:00.000,2018-06-17 15:02:00.000,2018-06-17 13:12:00.000,2018-06-17 14:29:00.000,2018-06-17 15:02:00.000
24,403,2016-02-13 10:44:42,B8.5,419.562555,335.575594,401.136993,292.191010,119.807999,160.0,Quiet Sun,...,341.232994,461.040993,212.191010,372.191010,2016-02-13 10:58:00.000,2016-02-13 11:01:00.000,2016-02-13 11:06:00.000,2016-02-13 10:58:00.000,2016-02-13 11:01:00.000,2016-02-13 11:06:00.000
25,403,2016-02-29 04:03:37,B6.9,53.907844,-32.523403,66.003899,-10.387700,119.807999,160.0,Quiet Sun,...,6.099899,125.907898,-90.387700,69.612300,2016-02-29 04:19:00.000,2016-02-29 04:30:00.000,2016-02-29 04:41:00.000,2016-02-29 04:19:00.000,2016-02-29 04:30:00.000,2016-02-29 04:41:00.000
26,404,2016-04-19 18:47:20,B4.3,893.381910,248.330836,911.744995,191.507996,119.807999,160.0,Quiet Sun,...,851.840996,971.648994,111.507996,271.507996,2016-04-19 19:26:00.000,2016-04-19 19:34:00.000,2016-04-19 19:42:00.000,2016-04-19 19:26:00.000,2016-04-19 19:34:00.000,2016-04-19 19:42:00.000
27,404,2016-04-20 07:32:13,B4.7,914.970288,242.280243,951.931030,211.507996,119.807999,160.0,Quiet Sun,...,892.027031,1011.835030,131.507996,291.507996,2016-04-20 07:31:00.000,2016-04-20 07:41:00.000,2016-04-20 07:46:00.000,2016-04-20 07:31:00.000,2016-04-20 07:41:00.000,2016-04-20 07:46:00.000
28,404,2016-05-13 04:55:28,B3.1,576.772960,190.830221,611.351990,189.677002,119.807999,160.0,Quiet Sun,...,551.447990,671.255989,109.677002,269.677002,2016-05-13 05:08:00.000,2016-05-13 05:09:00.000,2016-05-13 05:11:00.000,2016-05-13 05:08:00.000,2016-05-13 05:09:00.000,2016-05-13 05:11:00.000
29,404,2016-05-14 07:07:19,B7.6,751.011981,172.858943,765.476990,170.865997,119.807999,160.0,Quiet Sun,...,705.572990,825.380989,90.865997,250.865997,2016-05-14 07:44:00.000,2016-05-14 07:52:00.000,2016-05-14 07:58:00.000,2016-05-14 07:44:00.000,2016-05-14 07:52:00.000,2016-05-14 07:58:00.000
30,404,2016-05-20 00:50:51,B2.6,-127.520618,-66.276031,-75.610298,-121.768997,119.807999,160.0,Quiet Sun,...,-135.514297,-15.706299,-201.768997,-41.768997,2016-05-20 00:55:00.000,2016-05-20 00:59:00.000,2016-05-20 01:02:00.000,2016-05-20 00:55:00.000,2016-05-20 00:59:00.000,2016-05-20 01:02:00.000
31,403,2016-07-20 02:37:43,C1.6,473.464941,-26.492045,477.135010,-47.881001,119.807999,160.0,Quiet Sun,...,417.231010,537.039009,-127.881001,32.118999,2016-07-20 02:40:00.000,2016-07-20 02:49:00.000,2016-07-20 02:59:00.000,2016-07-20 02:40:00.000,2016-07-20 02:49:00.000,2016-07-20 02:59:00.000
32,404,2016-09-27 12:25:27,B2.5,673.753284,-307.493219,680.591003,-342.140991,119.807999,160.0,Quiet Sun,...,620.687004,740.495003,-422.140991,-262.140991,2016-09-27 12:49:00.000,2016-09-27 12:54:00.000,2016-09-27 12:58:00.000,2016-09-27 12:49:00.000,2016-09-27 12:54:00.000,2016-09-27 12:58:00.000
33,404,2016-10-14 11:05:26,B9.4,869.102432,-250.921809,825.442993,-300.179993,119.807999,160.0,Quiet Sun,...,765.538994,885.346992,-380.179993,-220.179993,2016-10-14 11:19:00.000,2016-10-14 11:26:00.000,2016-10-14 11:33:00.000,2016-10-14 11:19:00.000,2016-10-14 11:26:00.000,2016-10-14 11:33:00.000
34,404,2016-11-30 14:07:02,C1.0,-665.139483,-133.800164,-693.880981,-166.505005,119.807999,160.0,Quiet Sun,...,-753.784981,-633.976982,-246.505005,-86.505005,2016-11-30 15:00:00.000,2016-11-30 15:07:00.000,2016-11-30 15:11:00.000,2016-11-30 15:00:00.000,2016-11-30 15:07:00.000,2016-11-30 15:11:00.000
35,404,2017-04-22 14:03:42,B2.1,-334.466036,292.084481,-308.917999,223.792007,119.807999,160.0,Quiet Sun,...,-368.821999,-249.014000,143.792007,303.792007,2017-04-22 14:52:00.000,2017-04-22 14:58:00.000,2017-04-22 15:01:00.000,2017-04-22 14:52:00.000,2017-04-22 14:58:00.000,2017-04-22 15:01:00.000
36,404,2017-05-28 00:23:17,B3.8,765.763238,242.883670,746.937988,163.712997,119.807999,160.0,Quiet Sun,...,687.033989,806.841988,83.712997,243.712997,2017-05-28 00:55:00.000,2017-05-28 01:00:00.000,2017-05-28 01:03:00.000,2017-05-28 00:55:00.000,2017-05-28 01:00:00.000,2017-05-28 01:03:00.000
37,403,2017-05-28 15:20:42,B3.0,835.359909,236.716175,816.056030,159.623001,119.807999,160.0,Quiet Sun,...,756.152031,875.960030,79.623001,239.623001,2017-05-28 15:42:00.000,2017-05-28 15:52:00.000,2017-05-28 15:57:00.000,2017-05-28 15:42:00.000,2017-05-28 15:52:00.000,2017-05-28 15:57:00.000
38,404,2017-05-29 10:48:25,B2.3,902.543356,225.152534,880.747986,155.914993,119.807999,160.0,Quiet Sun,...,820.843987,940.651985,75.914993,235.914993,2017-05-29 11:35:00.000,2017-05-29 11:41:00.000,2017-05-29 11:47:00.000,2017-05-29 11:35:00.000,2017-05-29 11:41:00.000,2017-05-29 11:47:00.000
39,404,2015-05-10 13:09:33,C2.2,-296.547806,270.977659,-250.339996,207.873001,119.807999,160.0,Quiet Sun,...,-310.243996,-190.435997,127.873001,287.873001,2015-05-10 12:45:00.000,2015-05-10 13:03:00.000,2015-05-10 13:23:00.000,2015-05-10 12:45:00.000,2015-05-10 13:03:00.000,2015-05-10 13:23:00.000
40,404,2015-06-21 02:08:34,M2.7,-246.412361,149.407455,-265.708008,214.897995,119.807999,160.0,Quiet Sun,...,-325.612007,-205.804008,134.897995,294.897995,2015-06-21 02:04:00.000,2015-06-21 02:34:00.000,2015-06-21 03:11:00.000,2015-06-21 02:04:00.000,2015-06-21 02:34:00.000,2015-06-21 03:11:00.000
41,404,2015-12-16 04:47:27,B7.0,6.081072,-279.083943,20.959499,-227.628006,119.807999,160.0,Quiet Sun,...,-38.944500,80.863499,-307.628006,-147.628006,2015-12-16 05:44:00.000,2015-12-16 05:48:00.000,2015-12-16 05:53:00.000,2015-12-16 05:44:00.000,2015-12-16 05:48:00.000,2015-12-16 05:53:00.000
42,403,2014-01-08 12:01:32,C3.6,190.249605,-91.313893,133.009995,-93.351601,119.807999,160.0,Quiet Sun,...,73.105995,192.913994,-173.351601,-13.351601,2014-01-08 11:56:00.000,2014-01-08 12:04:00.000,2014-01-08 12:17:00.000,2014-01-08 11:56:00.000,2014-01-08 12:04:00.000,2014-01-08 12:17:00.000
43,403,2014-01-11 12:30:27,C6.5,692.625075,-128.321860,635.137024,-108.768997,119.807999,160.0,Quiet Sun,...,575.233025,695.041023,-188.768997,-28.768997,2014-01-11 13:00:00.000,2014-01-11 13:10:00.000,2014-01-11 13:22:00.000,2014-01-11 13:00:00.000,2014-01-11 13:10:00.000,2014-01-11 13:22:00.000
44,404,2014-08-07 03:09:13,B7.7,297.359239,-392.658056,289.589996,-439.279999,119.807999,160.0,Quiet Sun,...,229.685997,349.493996,-519.279999,-359.279999,2014-08-07 03:05:00.000,2014-08-07 03:09:00.000,2014-08-07 03:17:00.000,2014-08-07 03:05:00.000,2014-08-07 03:09:00.000,2014-08-07 03:17:00.000
45,403,2014-08-15 02:27:25,B6.2,-466.391154,175.757863,-456.462006,117.406998,119.807999,160.0,Quiet Sun,...,-516.366005,-396.558006,37.406998,197.406998,2014-08-15 02:34:00.000,2014-08-15 02:39:00.000,2014-08-15 02:47:00.000,2014-08-15 02:34:00.000,2014-08-15 02:39:00.000,2014-08-15 02:47:00.000
46,404,2011-03-19 15:34:09,B2.7,320.211861,296.903165,356.609009,331.433014,119.807999,160.0,Quiet Sun,...,296.705009,416.513008,251.433014,411.433014,2011-03-19 16:21:00.000,2011-03-19 16:34:00.000,2011-03-19 16:52:00.000,2011-03-19 16:21:00.000,2011-03-19 16:34:00.000,2011-03-19 16:52:00.000
47,404,2011-04-11 13:23:00,B7.2,-502.142377,297.172908,-534.364990,301.614990,119.807999,160.0,Quiet Sun,...,-594.268990,-474.460991,221.614990,381.614990,2011-04-11 12:49:00.000,2011-04-11 13:10:00.000,2011-04-11 13:26:00.000,2011-04-11 12:49:00.000,2011-04-11 13:10:00.000,2011-04-11 13:26:00.000
48,404,2011-04-15 02:30:26,B8.8,222.237960,317.038580,198.867996,304.395996,119.807999,160.0,Quiet Sun,...,138.963997,258.771996,224.395996,384.395996,2011-04-15 02:43:00.000,2011-04-15 02:47:00.000,2011-04-15 02:52:00.000,2011-04-15 02:43:00.000,2011-04-15 02:47:00.000,2011-04-15 02:52:00.000
49,404,2011-07-11 00:29:26,B3.6,214.474807,-361.715296,236.643997,-405.817993,119.807999,160.0,Quiet Sun,...,176.739998,296.547997,-485.817993,-325.817993,2011-07-11 01:12:00.000,2011-07-11 01:17:00.000,2011-07-11 01:20:00.000,2011-07-11 01:12:00.000,2011-07-11 01:17:00.000,2011-07-11 01:20:00.000
50,403,2013-01-12 19:08:20,C3.9,-286.555073,141.533609,-323.786011,195.296997,119.807999,160.0,Quiet Sun,...,-383.690010,-263.882011,115.296997,275.296997,2013-01-12 19:26:00.000,2013-01-12 19:33:00.000,2013-01-12 19:38:00.000,2013-01-12 19:26:00.000,2013-01-12 19:33:00.000,2013-01-12 19:38:00.000
51,404,2013-08-02 10:48:10,B9.7,191.178621,-343.986357,140.580994,-389.441986,119.807999,160.0,Quiet Sun,...,80.676994,200.484993,-469.441986,-309.441986,2013-08-02 11:08:00.000,2013-08-02 11:15:00.000,2013-08-02 11:24:00.000,2013-08-02 11:08:00.000,2013-08-02 11:15:00.000,2013-08-02 11:24:00.000
52,403,2013-12-28 10:38:41,C1.2,491.649901,-295.964737,439.647003,-239.041000,119.807999,160.0,Quiet Sun,...,379.743004,499.551003,-319.041000,-159.041000,2013-12-28 11:00:00.000,2013-12-28 11:18:00.000,2013-12-28 11:32:00.000,2013-12-28 11:00:00.000,2013-12-28 11:18:00.000,2013-12-28 11:32:00.000
53,404,2012-06-13 11:05:35,M1.2,-323.556296,-315.198557,-345.769989,-333.746002,119.807999,160.0,Quiet Sun,...,-405.673988,-285.865990,-413.746002,-253.746002,2012-06-13 11:29:00.000,2012-06-13 13:17:00.000,2012-06-13 14:31:00.000,2012-06-13 11:29:00.000,2012-06-13 13:17:00.000,2012-06-13 14:31:00.000

In [31]:
filtered_df['filename']

0     eis_20230209_122050.data.h5
1     eis_20230413_000702.data.h5
2     eis_20230510_140744.data.h5
3     eis_20230521_235518.data.h5
4     eis_20230523_070147.data.h5
5     eis_20230524_191241.data.h5
6     eis_20220421_125013.data.h5
7     eis_20220428_234108.data.h5
8     eis_20220526_122442.data.h5
9     eis_20220724_142113.data.h5
10    eis_20220729_140113.data.h5
11    eis_20221002_110320.data.h5
12    eis_20221002_110320.data.h5
13    eis_20200409_083843.data.h5
14    eis_20201027_155040.data.h5
15    eis_20201028_010513.data.h5
16    eis_20201101_002013.data.h5
17    eis_20201105_222813.data.h5
18    eis_20201115_214810.data.h5
19    eis_20201119_205240.data.h5
20    eis_20201125_024310.data.h5
21    eis_20210824_124800.data.h5
22    eis_20211116_115305.data.h5
23    eis_20180617_143311.data.h5
24    eis_20160213_104442.data.h5
25    eis_20160229_040337.data.h5
26    eis_20160419_184720.data.h5
27    eis_20160420_073213.data.h5
28    eis_20160513_045528.data.h5
29    eis_20160514_070719.data.h5
30    eis_20160520_005051.data.h5
31    eis_20160720_023743.data.h5
32    eis_20160927_122527.data.h5
33    eis_20161014_110526.data.h5
34    eis_20161130_140702.data.h5
35    eis_20170422_140342.data.h5
36    eis_20170528_002317.data.h5
37    eis_20170528_152042.data.h5
38    eis_20170529_104825.data.h5
39    eis_20150510_130933.data.h5
40    eis_20150621_020834.data.h5
41    eis_20151216_044727.data.h5
42    eis_20140108_120132.data.h5
43    eis_20140111_123027.data.h5
44    eis_20140807_030913.data.h5
45    eis_20140815_022725.data.h5
46    eis_20110319_153409.data.h5
47    eis_20110411_132300.data.h5
48    eis_20110415_023026.data.h5
49    eis_20110711_002926.data.h5
50    eis_20130112_190820.data.h5
51    eis_20130802_104810.data.h5
52    eis_20131228_103841.data.h5
53    eis_20120613_110535.data.h5
Name: filename, dtype: object